### ISSUE TITLE
[Bug] citrix_delivery_group documentation is flawed

### ISSUE THREAD

**Issue by Idem** [citrix/terraform-provider-citrix#102]
## Describe the bug

*Summary of the issue*

citrix_delivery_group documentation is flawed
Most of the optional properties describe as [autoscale_settings](https://github.com/citrix/terraform-provider-citrix/blob/main/docs/resources/delivery_group.md#nested-schema-for-autoscale_settings) nested schema applies to citrix_delivery_group schema instead.

Including (at least):
- timezone
- off_peak*
- peak*

**Comment by zhuolun-citrix** [comment]
Hi @Idem ,

Can you please explain why those properties you mentioned applies to `citrix_delivery_group` schema?

Please be aware that the schema structure we have in terraform is organized differently from the API request model of the corresponding API. 

Thank you,
Zhuolun

**Comment by Idem** [comment]
My bad. No issue here.
