### ISSUE TITLE
Enhancement: Add delivery configuration to application resource

### ISSUE THREAD

**Issue by prasanthrs6** [citrix/terraform-provider-citrix#110]
## Describe the feature request
Add Delivery configuration to Application resource.

## Example:

Application Category: QA

**Comment by yashbhokare-citrix** [comment]
Hi @prasanthrs6,

Can you please share more details on exactly which all delivery configurations are you talking about?

Yash Bhokare

**Comment by prasanthrs6** [comment]
@yashbhokare-citrix This is specific Multi-session delivery groups. Here is a screenshot of the ask.

![snap](https://github.com/user-attachments/assets/5bc12527-0c94-41da-b616-1408e392d3a5)

**Comment by yashbhokare-citrix** [comment]
Hi @prasanthrs6,

Thanks for the clarification. We will work on adding this option for the application resource.

Yash Bhokare

**Comment by AlanCitrix** [comment]
We introduced `citrix_application.application_category_path` in v1.0.3. Please try it out and let us know if there's any issues!
