### ISSUE TITLE
[Bug] Hypervisor Resource Pool for Azure; unexpected new value: .tenants: was null, but now

### ISSUE THREAD

**Issue by Xufuru** [citrix/terraform-provider-citrix#113]
I'm trying to create the Hypervisor Resource Pool for Azure using the Terraform module, but I keep encountering this error:
��� Error: Error creating Hypervisor Resource Pool for Azure
��� 
���   with module.vdr["VDR-WRRUN1"].module.citrix.citrix_azure_hypervisor_resource_pool.azure-hypervisor-resource-pool,
���   on modules/citrix/main.tf line 27, in resource "citrix_azure_hypervisor_resource_pool" "azure-hypervisor-resource-pool":
���   27: resource "citrix_azure_hypervisor_resource_pool" "azure-hypervisor-resource-pool" {
��� 
��� TransactionId: 
��� Failed to resolve region Italy North, error: 502 Bad Gateway

I tried creating the resource manually with the same settings used in the Terraform code, and I can do it without any issues.

**Comment by aneeshk-citrix** [comment]
Hi @Xufuru,

We are taking a look at this issue.

Are you able to consistently reproduce this?

Thanks,
Aneesh

**Comment by Xufuru** [comment]
The error appears randomly when I run my code and alternates with two other errors, which I have attached below, also related to the machine catalog.

Other error 1: 
��� Error: Error creating Hypervisor Resource Pool for Azure
��� 
���   with module.vdr["VDR-WRRUN5"].module.citrix.citrix_azure_hypervisor_resource_pool.azure-hypervisor-resource-pool,
���   on modules/citrix/main.tf line 12, in resource "citrix_azure_hypervisor_resource_pool" "azure-hypervisor-resource-pool":
���   12: resource "citrix_azure_hypervisor_resource_pool" "azure-hypervisor-resource-pool" {
��� 
��� TransactionId: 6dca5fa8-8446-4fce-a5ad-c5458c9f35d8
��� Failed to resolve virtual network vnt-itn-tecp-001-VDR-WRRUN5 in region
��� Italy North, error: could not find resource

Other error, about machine catalog: 
��� Error: Provider produced inconsistent result after apply
��� 
��� When applying changes to
��� module.vdr["VDR-WRRUN4"].module.citrix.citrix_machine_catalog.wrkgpu-machine-catalog,
��� provider "provider[\"registry.terraform.io/citrix/citrix\"]" produced an
��� unexpected new value: .scopes: actual set element
��� cty.StringVal("5734c93f-f257-4be4-babd-037546110136") does not correlate
��� with any element in plan.
��� 
��� This is a bug in the provider, which should be reported in the provider's
��� own issue tracker.
���
���
��� Error: Provider produced inconsistent result after apply
��� 
��� When applying changes to
��� module.vdr["VDR-WRRUN4"].module.citrix.citrix_machine_catalog.wrkgpu-machine-catalog,
��� provider "provider[\"registry.terraform.io/citrix/citrix\"]" produced an
��� unexpected new value: .scopes: length changed from 0 to 1.
��� 
��� This is a bug in the provider, which should be reported in the provider's
��� own issue tracker.
���
���
��� Error: Provider produced inconsistent result after apply
��� 
��� When applying changes to
��� module.vdr["VDR-WRRUN4"].module.citrix.citrix_machine_catalog.wrkgpu-machine-catalog,
��� provider "provider[\"registry.terraform.io/citrix/citrix\"]" produced an
��� unexpected new value: .tenants: was null, but now
��� cty.SetVal([]cty.Value{cty.StringVal("38d733c2-7f44-4da3-a2da-cbe1257a159d")}).
��� 
��� This is a bug in the provider, which should be reported in the provider's
��� own issue tracker.

**Comment by aneeshk-citrix** [comment]
Hi @Xufuru,

Can you please share the config that you are trying to apply? That will help us in figuring out the issue.

Thanks,
Aneesh

**Comment by Xufuru** [comment]
Here my terraform code: 
# Hypervisor Resource Pool Hypervisor
resource "citrix_azure_hypervisor_resource_pool" "azure-hypervisor-resource-pool" {
  name                           = upper("RP-AZ-NI-TECS-P-${var.vdr_name}")
  hypervisor                     = local.azure_hypervisor_id
  region                         = var.location
  virtual_network_resource_group = var.resource_group_vdr
  virtual_network                = var.virtual_network
  subnets                        = [var.subnet_vdi]
}

resource "time_sleep" "wait_5min_for_resource_pool" {
  depends_on      = [citrix_azure_hypervisor_resource_pool.azure-hypervisor-resource-pool]
  create_duration = "300s"
}

data "azurerm_snapshot" "wrkdoc_machine" {
  name                = local.vm_doc_master_template
  resource_group_name = var.resource_group_automation
}

data "azurerm_snapshot" "wrkgpu_machine" {
  name                = local.vm_gpu_master_template
  resource_group_name = var.resource_group_automation
}

# Get Zone
data "citrix_zone" "core-zone" {
  name = local.citrix_zone_name
}

############################### MACHINE CATALOG ##############################################################################

# Machine Catalog for GPU machines
resource "citrix_machine_catalog" "wrkgpu-machine-catalog" {
  depends_on               = [time_sleep.wait_5min_for_resource_pool]
  name                     = "Wrkgpu-${var.vdr_name}"
  zone                     = data.citrix_zone.core-zone.id
  scopes                   = ["5734c93f-f257-4be4-babd-037546110136"]
  # tenants                  = ["38d733c2-7f44-4da3-a2da-cbe1257a159d"]
  allocation_type          = local.mc_allocation_type
  session_support          = local.mc_session_support
  provisioning_type        = local.mc_provisioning_type
  minimum_functional_level = local.mc_minimum_functional_level
  provisioning_scheme = {
    hypervisor               = local.azure_hypervisor_id
    hypervisor_resource_pool = citrix_azure_hypervisor_resource_pool.azure-hypervisor-resource-pool.id
    identity_type            = "ActiveDirectory"
    machine_domain_identity = {
      domain                   = local.domain
      domain_ou                = local.domain_ou
      service_account          = var.admin_username
      service_account_password = var.admin_password
    }
    azure_machine_config = {
      storage_type       = var.disk_sa_type
      use_managed_disks  = true
      service_offering   = local.wrkgpu_mc_config.service_offering
      vda_resource_group = var.resource_group_vdr
      azure_master_image = {
        resource_group = var.resource_group_automation
        master_image   = data.azurerm_snapshot.wrkgpu_machine.name
      }
      machine_profile = {
        machine_profile_resource_group = var.resource_group_automation
        machine_profile_vm_name        = local.wrkgpu_mc_config.machine_profile_vm_name
      }
      license_type = "Windows_Client"
    }
    network_mapping = [
      {
        network_device = "0"
        network        = var.subnet_vdi
      }
    ]
    # GPU Machine count must be at least 5 (2 DM, 1 User, 1 DM Spare, 1 User Spare)
    number_of_total_machines = var.vm_gpu_count > 4 ? var.vm_gpu_count : 5
    machine_account_creation_rules = {
      naming_scheme      = "G-##-${var.vdr_name}"
      naming_scheme_type = "Numeric"
    }
  }
  lifecycle {
    ignore_changes = [
      zone
    ]
  }
}

**Comment by Xufuru** [comment]
# Hypervisor Resource Pool Hypervisor
resource "citrix_azure_hypervisor_resource_pool" "azure-hypervisor-resource-pool" {
  name                           = upper("RP-AZ-NI-TECS-P-${var.vdr_name}")
  hypervisor                     = local.azure_hypervisor_id
  region                         = var.location
  virtual_network_resource_group = var.resource_group_vdr
  virtual_network                = var.virtual_network
  subnets                        = [var.subnet_vdi]
}

resource "time_sleep" "wait_5min_for_resource_pool" {
  depends_on      = [citrix_azure_hypervisor_resource_pool.azure-hypervisor-resource-pool]
  create_duration = "300s"
}

data "azurerm_snapshot" "wrkdoc_machine" {
  name                = local.vm_doc_master_template
  resource_group_name = var.resource_group_automation
}

data "azurerm_snapshot" "wrkgpu_machine" {
  name                = local.vm_gpu_master_template
  resource_group_name = var.resource_group_automation
}

# Get Zone
data "citrix_zone" "core-zone" {
  name = local.citrix_zone_name
}

############################### MACHINE CATALOG ##############################################################################

# Machine Catalog for GPU machines
resource "citrix_machine_catalog" "wrkgpu-machine-catalog" {
  depends_on               = [time_sleep.wait_5min_for_resource_pool]
  name                     = "Wrkgpu-${var.vdr_name}"
  zone                     = data.citrix_zone.core-zone.id
  scopes                   = ["xxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
  allocation_type          = local.mc_allocation_type
  session_support          = local.mc_session_support
  provisioning_type        = local.mc_provisioning_type
  minimum_functional_level = local.mc_minimum_functional_level
  provisioning_scheme = {
    hypervisor               = local.azure_hypervisor_id
    hypervisor_resource_pool = citrix_azure_hypervisor_resource_pool.azure-hypervisor-resource-pool.id
    identity_type            = "ActiveDirectory"
    machine_domain_identity = {
      domain                   = local.domain
      domain_ou                = local.domain_ou
      service_account          = var.admin_username
      service_account_password = var.admin_password
    }
    azure_machine_config = {
      storage_type       = var.disk_sa_type
      use_managed_disks  = true
      service_offering   = local.wrkgpu_mc_config.service_offering
      vda_resource_group = var.resource_group_vdr
      azure_master_image = {
        resource_group = var.resource_group_automation
        master_image   = data.azurerm_snapshot.wrkgpu_machine.name
      }
      machine_profile = {
        machine_profile_resource_group = var.resource_group_automation
        machine_profile_vm_name        = local.wrkgpu_mc_config.machine_profile_vm_name
      }
      license_type = "Windows_Client"
    }
    network_mapping = [
      {
        network_device = "0"
        network        = var.subnet_vdi
      }
    ]
    # GPU Machine count must be at least 5 (2 DM, 1 User, 1 DM Spare, 1 User Spare)
    number_of_total_machines = var.vm_gpu_count > 4 ? var.vm_gpu_count : 5
    machine_account_creation_rules = {
      naming_scheme      = "G-##-${var.vdr_name}"
      naming_scheme_type = "Numeric"
    }
  }
  lifecycle {
    ignore_changes = [
      zone
    ]
  }
}

**Comment by aneeshk-citrix** [comment]
Hi @Xufuru,

We have identified the issue and will have a fix for this with the next release.

Thanks,
Aneesh

**Comment by aneeshk-citrix** [comment]
Hi @Xufuru,

Do you have any scopes applied on the hypervisor that you are creating the machine catalog for?

The machine catalog config shows you have a scope applied but the error says  `.scopes: length changed from 0 to 1.` which means there were no scopes in the config. 

Please specify the config for all the resources that you are applying.

Thanks,
Aneesh

**Comment by Xufuru** [comment]
I try adding the scopes as a value in my code, nut i get the same error with the tenants.

��� Error: Provider produced inconsistent result after apply
���
��� When applying changes to
��� module.vdr["VDR-WRRUN4"].module.citrix.citrix_machine_catalog.wrkgpu-machine-catalog,
��� provider "provider["registry.terraform.io/citrix/citrix"]" produced an
��� unexpected new value: .tenants: was null, but now
��� cty.SetVal([]cty.Value{cty.StringVal("38d733c2-7f44-4da3-a2da-cbe1257a159d")}).
���
��� This is a bug in the provider, which should be reported in the provider's
��� own issue tracker.

**Comment by AlanCitrix** [comment]
Thanks, we are still looking into this issue. In the meantime can we try 2 things?

1. Can you send us the TF logs using the instructions @aneeshk-citrix posted above. This will help us to narrow down the problem and engage other teams at Citrix if necessary. These can be sent via email if you prefer.

2. What happens if you remove `scopes` and `tenants` from the machine catalogs? Looking at [our docs](https://docs.citrix.com/en-us/citrix-daas/manage-deployment/delegated-administration.html#create-a-tenant-customer), the `tenant` property should automatically be set from the `scope`:

> The tenant property is assigned at a scope level. Machine catalogs, delivery groups, applications, and connections inherit the tenant property from the applicable scope.

From the same doc, it also appears the the scope should be inherited from the hypervisor automatically:

> When using a tenant scope, be aware of the following considerations:
> The tenant property is assigned in the following order: Hosting > Machine Catalogs > Delivery Groups > Applications. Lower-> level objects rely on higher-level objects to inherit the tenant property from

We think this automatic mechanism is what is causing some issues in the provider so we will research it further, but I wanted to see if this can unblock you.
