### ISSUE TITLE
[Bug] Unable to configure StoreFront Farm Mapping

### ISSUE THREAD

**Issue by dhermanconsulting** [citrix/terraform-provider-citrix#114]
## Describe the bug

*Unable to configure StoreFront Farm Mapping*

I'm having lots of trouble with the UFM mappings for StoreFront. Some of the documentation is unclear, and it also refers to a config item that doesn't seem to exist anymore ( citrix_stf_store_farm). Nontheless, I tried to put together a minimal test example but I get a PowerShell execution error when attempting to apply.

**terraform.exe apply -parallelism=1**
**Resource impacted:**

StoreFront UFM

## Versions
Terraform v1.9.5[Uploading terraform.log…]()

on windows_amd64
+ provider registry.terraform.io/citrix/citrix v1.0.1
Windows 11

StoreFront: 2402 LTSR CU1

## Terraform configuration files
(See attached for a minimum example)

## Terraform console output
*Paste the output from Terraform CLI including any errors and the transactionIds if present.*

citrix_stf_user_farm_mapping.example-stf-user-farm-mapping: Creating...
╷
│ Error: Error adding StoreFront UserFarmMapping
│
│   with citrix_stf_user_farm_mapping.example-stf-user-farm-mapping,
│   on ufm.tf line 71, in resource "citrix_stf_user_farm_mapping" "example-stf-user-farm-mapping":
│   71: resource "citrix_stf_user_farm_mapping" "example-stf-user-farm-mapping" {
│
│ Error Message: error executing command: Add-STFUserFarmMapping
│  Error Message:
│  Serialized XML is nested too deeply. Line 1, position 14184.
│     + CategoryInfo          : OperationStopped: (192.168.125.128:String) [], PSRemotingTransportException
│     + FullyQualifiedErrorId : JobFailure
│     + PSComputerName        : 192.168.125.128
│
│

## Terraform log file
Attached

[terraform.log](https://dhermanconsulting.co.uk/dump/terraform.log)

[minimal_example.txt](https://github.com/user-attachments/files/16866729/minimal_example.txt)

**Comment by AlanCitrix** [comment]
We fixed the example, see the updated one here: https://registry.terraform.io/providers/citrix/citrix/latest/docs/resources/stf_user_farm_mapping

For your issue see @sourav-citrix's comment about the farm name above. If you are still experiencing any issue please reopen this bug or file a new one.
