### ISSUE TITLE
[Bug] Error: citrix_cloud_resource_location / Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Cedronimo** [citrix/terraform-provider-citrix#115]
I sometimes get an error when i try to create a Citrix Resource Location and corresponding Zone in Citrix Cloud:

```git
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.citrix_rl.citrix_zone.zone, provider
│ "provider[\"registry.terraform.io/citrix/citrix\"]" produced an unexpected
│ new value: .resource_location_id: was
│ cty.StringVal("[_Citrix-Resourcelocation-ID_]"), but now
│ cty.StringVal("[_New-Random-Resourcelocation-ID_]").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

Terraform code looks like this:

```terraform
# Create Citrix Resource Location
resource "citrix_cloud_resource_location" "citrix_rl" {
  name = var.citrix_resource_location
}

# Create Citrix Zone
resource "citrix_zone" "zone" {
  resource_location_id = citrix_cloud_resource_location.citrix_rl.id
}
```

When i run apply:
```git
module.citrix_rl.citrix_cloud_resource_location.citrix_rl: Creating...
module.citrix_rl.citrix_cloud_resource_location.citrix_rl: Creation complete after 1s [id="[_Citrix-Resourcelocation-ID_]"]
module.citrix_rl.citrix_zone.zone: Creating...
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.citrix_rl.citrix_zone.zone, provider
│ "provider[\"registry.terraform.io/citrix/citrix\"]" produced an unexpected
│ new value: .resource_location_id: was
│ cty.StringVal("[_Citrix-Resourcelocation-ID_]"), but now
│ cty.StringVal("[_New-Random-Resourcelocation-ID_]").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
It looks like, when it tries to create the zone with the existing Resource Location ID, it creates a new Resource Location ID which doesn't exist.

When I logon to Citrix DaaS the Resource Location "[_Citrix-Resourcelocation-ID_]" is there, but the deployment has stopped at the error.

This is with Citrix Provider 1.0.0 and happens only sometimes. If I run apply again it may work.

**Comment by zhuolun-citrix** [comment]
Hi @Cedronimo ,

May I ask how frequent are you recreating the resource location & zone? Did you try to remove a zone and a resource location, then immediately create a new resource location with the same name and the zone?

Thank you,
Zhuolun

**Comment by Cedronimo** [comment]
Hi @zhuolun-citrix ,

Yes, thank you, that will be the problem, it's a test environment that we often destroy and re-depoy.

**Comment by dimi4ik** [comment]
Hello @zhuolun-citrix ,
After deleting, are we not allowed to immediately create a new zone location and zone? 
How long should we wait? 10 minutes or longer?

**Comment by zhuolun-citrix** [comment]
Hi @dimi4ik ,

I would recommend waiting for at least 5min.
