### ISSUE TITLE
[Bug] Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by TimBennett13** [citrix/terraform-provider-citrix#120]
## Describe the bug

*Summary of the issue*

On terraform apply a machine catalog is created but an error is thrown.
"Error: Provider produced inconsistent result after apply.  When applying changes to citrix_machine_catalog.DaaSMachineCatalog, provider "provider[\"registry.terraform.io/citrix/citrix\"]" produced an unexpected new value: .provisioning_scheme: inconsistent values for  sensitive attribute. This is a bug in the provider, which should be reported in the provider's own issue tracker."
 
## Versions
Terraform v1.7.5
on windows_amd64
+ provider registry.terraform.io/citrix/citrix v1.0.1
+ provider registry.terraform.io/hashicorp/azurerm v4.0.1

*DaaS*
## Log File ##
[citrix-provider-issue.txt](https://github.com/user-attachments/files/17030451/citrix-provider-issue.txt)

**Comment by TimBennett13** [comment]
Apply and destroy commands seem to work as expected.

**Comment by AlanCitrix** [comment]
Thanks for reporting the issue and attaching the logs. Looking at the logs it seems you are using Azure image gallery on a shared subscription. There is a bug in v1.0.1 with shared subscription: #117

We'll have a fix in our next release which should be out soon!

**Comment by AlanCitrix** [comment]
This should be fixed now, please let us know on #117 if there's still a problem.
