### ISSUE TITLE
[Feature] Restrict launches to machines with this tag

### ISSUE THREAD

**Issue by j7lloyd** [citrix/terraform-provider-citrix#121]
## Describe the feature request
**Summary:** As the title implies, restrict desktops within a delivery group to run only on machines with a specific tag.

**Is this an enhancement to an existing resource or data source, if so which one?** Yes, this is an enhancement to the `citrix_delivery_group` resource.

**If this is a new resource or data source describe what it should do.** Introduce a `citrix_tags` resource to create and update tags, specifically machine tags, and a data source to read existing tags.

**Link to any docs that cover this feature:**
https://docs.citrix.com/en-us/citrix-daas/install-configure/delivery-groups-create.html#step-8-desktops-or-desktop-assignment-rules
https://docs.citrix.com/en-us/citrix-daas/manage-deployment/tags.html#tag-restrictions-for-a-desktop-or-an-application-group

**Link to any APIs that cover this feature:**
https://developer-docs.citrix.com/en-us/citrix-daas-service-apis/citrix-daas-rest-apis/apis/#/DeliveryGroups-APIs/DeliveryGroups-CreateDeliveryGroup
https://developer-docs.citrix.com/en-us/citrix-daas-service-apis/citrix-daas-rest-apis/apis/#/Machines-APIs/Machines-AddMachineTags
https://developer-docs.citrix.com/en-us/citrix-daas-service-apis/citrix-daas-rest-apis/apis/#/Tags-APIs

**Comment by xushengl** [comment]
Hi @j7lloyd 

Thanks for suggesting the citrix_tags resource and data source for managing tags. We will look into adding support to this feature

Best Regards,
Xusheng "Fred" Liu

**Comment by zhuolun-citrix** [comment]
Hi @j7lloyd ,

Thanks for letting us know. Reopening this issue.

We will add support for restricting desktop launches to machines with a specific tag in the next release.

Thank you,
Zhuolun
