### ISSUE TITLE
[Feature] Cloud Zone destroy and deleted Citrix Cloud Connector

### ISSUE THREAD

**Issue by dimi4ik** [citrix/terraform-provider-citrix#123]
*Thanks for taking the time to fill out this feature request! Before submitting this issue please check the [open feature requests](https://github.com/citrix/terraform-provider-citrix/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) to ensure the feature has not already been reported. If it has been reported give it a 👍*

## Describe the feature request
*Fill out the following questions and add any additional information.*
**Summary:**

Hello,

We are creating a new Citrix environment in Azure via a GitLab pipeline with all components (Cloud Connector, VDA using Terraform). As part of the CI/CD process, we need to repeatedly redeploy the entire Terraform setup and then completely delete it.

We have noticed that when performing a Terraform destroy on the Citrix zone, we encounter an error. 

Error: Error deleting resource location with id: ffa7e978-b72a-4897-8d42-57e3647a296b

/-/jobs/3373164#L205)│ TransactionId: f01cf1bd-139c-4bb5-8e37-195577229039
/-/jobs/3373164#L206)│ Error message: 400 Bad Request

The reason is that the deleted Citrix Cloud Connector still remains in the zone. This causes additional effort, as we have to manually uninstall and maintain the Citrix Cloud Connector.

Could you please check internally whether it is possible to call an API during the Terraform destroy of the zone that ensures the Cloud Connector is automatically deleted as well? When someone destroys the zone, they understand the implications, and I see no risk in also removing the Cloud Connector. If I manually remove the deleted Cloud Connector from the Citrix plan, the destroy process works without any issues.

If you have any further questions or need more details, please let me know.

**Is this an enhancement to an existing resource or data source, if so which one?**

# Exmaple for Cloud Zone
resource "citrix_cloud_resource_location" "example-resource-location" {
    name = "example-resource-location"
}

resource "citrix_zone" "example-cloud-zone" {
    resource_location_id = citrix_cloud_resource_location.example-resource-location.id
}

**If this is a new resource or data source describe what it should do.**

**Link to any docs that cover this feature:**
https://docs.citrix.com/

**Link to any APIs that cover this feature:**
https://developer-docs.citrix.com/

**Comment by dimi4ik** [comment]
@AlanCitrix Thank you for the very interesting idea 👍 with the variable "CITRIX_CLOUD_RESOURCE_LOCATION_FORCE_DELETE," and we will definitely adopt it. 💯

**Comment by AlanCitrix** [comment]
Great. The delete Connectors API is not public so we will put this on our roadmap and try to get it prioritized.

In the meantime if you are able to automate the Connector uninstallation, or just leave the resource location unmanaged by Terraform and reuse it between runs, that could be a workaround.
