### ISSUE TITLE
[Bug] Error while adding 2 additionals machine in the machine catalog

### ISSUE THREAD

**Issue by Xufuru** [citrix/terraform-provider-citrix#128]
Hi, i was trying to add 2 machine using the machine catalog created in another terraform run. My action was changing the number of the machine from 1 to 3 in the code (for the second run), so in that case, terraform would apply the change to the already existing machine catalog and add the 2 new machine, but i get this error: 

��� Error: Error updating Machine Catalog Wrkdoc-VDRWR0
��� 
���   with module.vdr["VDRWR0"].module.citrix.citrix_machine_catalog.wrkdoc-machine-catalog[0],
���   on modules/citrix/main.tf line 101, in resource "citrix_machine_catalog" "wrkdoc-machine-catalog":
���  101: resource "citrix_machine_catalog" "wrkdoc-machine-catalog" {
��� 
��� TransactionId: 1c4cc156-fe30-498f-9f89-9a8c19e3fd59
��� An error occurred while adding machine(s) to the Machine Catalog. 1 of 2
��� machines were added to the Machine Catalog.
���

This is my code: 
resource "citrix_machine_catalog" "wrkdoc-machine-catalog" {
  count      = var.users_doc_count > 0 ? 1 : 0 # if users got documental vm, this catalog will be created
  depends_on = [citrix_machine_catalog.wrkgpu-machine-catalog[0]]
  name       = "Wrkdoc-${var.vdr_name}"
  zone       = data.citrix_zone.core-zone.id
  allocation_type          = local.mc_allocation_type
  session_support          = local.mc_session_support
  provisioning_type        = local.mc_provisioning_type
  minimum_functional_level = local.mc_minimum_functional_level
  provisioning_scheme = {
    hypervisor               = local.azure_hypervisor_id
    hypervisor_resource_pool = citrix_azure_hypervisor_resource_pool.azure-hypervisor-resource-pool.id
    identity_type            = "ActiveDirectory"
    machine_domain_identity = {
      domain                   = local.domain
      domain_ou                = local.domain_ou
      service_account          = var.admin_username
      service_account_password = var.admin_password
    }
    azure_machine_config = {
      storage_type       = var.disk_sa_type
      use_managed_disks  = true
      service_offering   = local.wrkdoc_mc_config.service_offering
      vda_resource_group = var.resource_group_vdr
      azure_master_image = {
        resource_group = var.resource_group_automation
        master_image   = data.azurerm_snapshot.wrkdoc_machine.name
      }
      machine_profile = {
        machine_profile_resource_group = var.resource_group_automation
        machine_profile_vm_name        = local.wrkdoc_mc_config.machine_profile_vm_name
      }
      license_type = "Windows_Client"
    }
    network_mapping = [
      {
        network_device = "0"
        network        = var.subnet_vdi
      }
    ]
    number_of_total_machines = var.dm_doc_count + var.users_doc_count
    machine_account_creation_rules = {
      naming_scheme      = "D-##-${var.vdr_name}"
      naming_scheme_type = "Numeric"
    }
  }
  lifecycle {
    ignore_changes = [
      zone
    ]
  }
}

**Comment by aneeshk-citrix** [comment]
Hi @Xufuru,

Thank you for reporting this. We are looking into it.

Aneesh
