### ISSUE TITLE
[Bug] Azure resource pool network connection details issue

### ISSUE THREAD

**Issue by krz73** [citrix/terraform-provider-citrix#131]
We have found some issues after deploying resources with the terraform provider, especially in the resource pool part.
The main difference between this and manually created resource is in the network details.
All resources are in Azure.

Terraform created:
HostUnit az-customer1-prod-weu-001
**XDHyp:\Connections\**az-serviceconnection\West Europe.region\virtualprivatecloud.folder\**XDHyp:\Connections\**az-serviceconnection\West Europe.region\virtualprivatecloud.folder\rg-customer1-prod-weu-001.resourcegroup\vnet-customer1-prod-weu-001.virtualprivatecloud\snet-customer1-prod-weu-001.network

Manually created:
HostUnit az-manual-002
**XDHyp:\Connections**\az-serviceconnection\West Europe.region\virtualprivatecloud.folder\West Europe.region\virtualprivatecloud.folder\rg-customer1-prod-weu-001.resourcegroup\vnet-customer1-prod-weu-001.virtualprivatecloud\snet-customer1-prod-weu-001.network

_XDHyp:\Connections_ appears twice in the terraform created resource.
This leads to a missing NIC configuration on the Citrix DaaS portal when editing the Machine Catalog.
Tested additionally with 2 NICs and 2 subnets in the same network.

![image](https://github.com/user-attachments/assets/375064a8-cb48-4627-b708-36742612d557)

resourcepool.tf
resource "citrix_azure_hypervisor_resource_pool" "resourcePool" {
    name                            = "az-${var.projectName}-${var.environment}-weu-${var.instance}"
    hypervisor                      = data.citrix_hypervisor.azureHypervisor.id
    region                          = azurerm_resource_group.rg.location
    virtual_network_resource_group  = azurerm_resource_group.rg.name
    virtual_network                 = azurerm_virtual_network.vnet.name
    subnets                         = [azurerm_subnet.subnet.name, azurerm_subnet.subnet2.name]
}

All deployments are done with Azure Pipelines, no error during deployment and the network mapping is working as expected in the end. We can reproduce the issue every time.

## Versions
**Terraform:** 1.9.5 x64 (latest)
**citrix/citrix provider:** 1.0.4 (was also in 1.0.3)
**Operation system:** ubuntu-latest/windows-lates

**Comment by aneeshk-citrix** [comment]
Hi @krz73,

Thanks for reporting this. We're working on a fix.

Aneesh
