### ISSUE TITLE
[Bug] "machine_catalog_folder_path" in resource "citrix_machine_catalog"

### ISSUE THREAD

**Issue by Cedronimo** [citrix/terraform-provider-citrix#138]
Bug Report Summary:

We are using provider Version 1.0.4

When creating a Citrix Machine Catalog wit a machine_catalog_folder_path value, the Application Folder name is incorrectly combined with the Machine Catalog name, leading to an invalid naming format. Instead of treating the Application Folder as a separate directory path, it gets merged into the Machine Catalog name.

Example:

In the Terraform module, the Application Folder is specified as "folder", and the Machine Catalog name is "MACHINE-CATALOG".

Terraform Code:
```hcl
module "citrix_mc" {
  ...
  citrix_machine_catalog_folder_path = "folder"
  citrix_machine_catalog_name = "MACHINE-CATALOG"
  ...
}
```

In Citrix DaaS, the machine catalog is created correctly first, even with the correct name and in the correct folder. But then the job terminates with the error

Resulting Error:
```cmd
Error: Error set tags for Machine Catalog folderMACHINE-CATALOG
TransactionId: a4fd91a9-eaf2-44f8-926c-2db35be3db1c
Error message: Machine Catalog not found.

Error: Error reading Machine Catalog folderMACHINE-CATALOG
TransactionId: 83aa3bf2-62e4-4222-a67d-980345c8bbb1
Error message: Machine Catalog not found.
```

PowerShell Log from DaaS:
```powershell
Create Machine Catalog 'folder\MACHINE-CATALOG'
New-BrokerCatalog -AdminFolder "folder\" -Name "MACHINE-CATALOG" ...
```
It looks like, the resulting Machine Catalog name becomes folderMACHINE-CATALOG, which causes errors when trying to read or set tags for the catalog.

**Comment by aneeshk-citrix** [comment]
Hi @Cedronimo,

Thanks for reporting this. We are aware of it and already have a fix ready. This fix should be available in the next release.

Aneesh
