### ISSUE TITLE
[Bug]Incorrect attribute value type MCS catalog in Azure

### ISSUE THREAD

**Issue by victorjayctx** [citrix/terraform-provider-citrix#142]
*Thanks for taking the time to fill out this bug report! Before submitting this issue please check the [open bugs](https://github.com/citrix/terraform-provider-citrix/issues?q=is%3Aissue+is%3Aopen+label%3Abug) to ensure the bug has not already been reported. If it has been reported give it a 👍*

*If this bug is present when using the Citrix service UI or REST APIs then it is not a bug in the provider but rather a bug in the underlying service or the environment. In some cases there can be an enhancement in the provider to handle the error better. Please open a feature request instead of a bug in this case. For more information see [CONTRIBUTING.md#provider-issue-vs-product-issue-vs-configuration-issue](https://github.com/citrix/terraform-provider-citrix/blob/main/CONTRIBUTING.md#provider-issue-vs-product-issue-vs-configuration-issue).*

## Describe the bug

*Summary of the issue*

**Terraform command (import, apply, etc):**
**Resource impacted:**

## Versions

Terraform v1.9.8
on windows_386
Windows 11 64-bit

# Terraform configuration files
*Paste or attach any relevant `.tf` files with secrets and identifying information removed.*

resource "citrix_machine_catalog" "example-machine-catalog" {
    name                        = var.machine_catalog_name
    description                 = "description for example catalog"
    allocation_type             = "Random"
    session_support             = "MultiSession"
	provisioning_type 			= "MCS"
    zone                        = citrix_zone.example-cloud-zone.id
    provisioning_scheme         = {
        hypervisor               = citrix_azure_hypervisor.azure-hypervisor.id
        hypervisor_resource_pool = citrix_azure_hypervisor_resource_pool.example-azure-rp.id
        identity_type            = "ActiveDirectory"
        machine_domain_identity  = {
            domain                   = var.domain_fqdn
            domain_ou                = var.domain_ou
            service_account          = var.domain_service_account
            service_account_password = var.domain_service_account_password
        }
        azure_machine_config     = {
            service_offering     = var.azure_service_offering
            use_managed_disks    = false
            azure_master_image = {
            #For Azure image gallery
                gallery_image = {
                    gallery    = var.azure_gallery_name
                    definition = var.azure_gallery_image_definition
                    version    = var.azure_gallery_image_version
                }
            }
            storage_type         = var.azure_storage_type
            use_managed_disks    = true
        }
        number_of_total_machines = 1
        machine_account_creation_rules = {
            naming_scheme = var.machine_catalog_naming_scheme
            naming_scheme_type = "Numeric"
        }
    }
}

## Terraform console output

attached
![tf-output](https://github.com/user-attachments/assets/b347b38e-2394-49f5-a7a0-28c97ce0e797)

**Comment by xushengl** [comment]
Hi @victorjayctx 

Thanks for posting this issue. When using the Azure Image Gallery, the `resource_group` attribute is still required. Could you please specify the resource group attribute and try again?


```
azure_master_image = {
	#For Azure image gallery
	resource_group = "{ResourceGroupPlaceholder}"
	gallery_image = {
		gallery = var.azure_gallery_name
		definition = var.azure_gallery_image_definition
		version = var.azure_gallery_image_version
	}
}
```

**Comment by victorjayctx** [comment]
thanks @xushengl  that worked!

**Comment by xushengl** [comment]
Glad to hear that! We will update our documentation accordingly to avoid confusion on the `resource_group` attribute. Thanks again for posting this issue!

Best Regards,
Xusheng "Fred" Liu
