### ISSUE TITLE
[Feature] Autoscaling Tagged Machines

### ISSUE THREAD

**Issue by SWO-andrew-shaffer** [citrix/terraform-provider-citrix#143]
**Summary:** When configuring Autoscaling of a delivery group, there is no option in the resource to enable the feature "Autoscaling Tagged Machines" and specifying a tag.

**Is this an enhancement to an existing resource or data source, if so which one?** Enhancement of `citrix_delivery_group`

**Link to any docs that cover this feature:**
https://docs.citrix.com/en-us/citrix-daas/manage-deployment/autoscale/autoscale-tagged-machines.html

**Link to any APIs that cover this feature:**
https://developer-docs.citrix.com/en-us/citrix-daas-service-apis/citrix-daas-rest-apis/apis/#/DeliveryGroups-APIs/DeliveryGroups-CreateDeliveryGroup
"RestrictAutoscaleTag" is set to a string for this functionality.

**Comment by aneeshk-citrix** [comment]
Hi @SWO-andrew-shaffer,

Thanks for bringing this to our attention. We will add this on the roadmap. This should be available within the next few releases.

Aneesh

**Comment by AlanCitrix** [comment]
This was added in v1.0.7: https://github.com/citrix/terraform-provider-citrix/releases/tag/v1.0.7

> Added support for restrict_autoscale_tag, peak_restrict_min_idle_untagged_percent, and off_peak_restrict_min_idle_untagged_percent attributes for the citrix_delivery_group resource
