### ISSUE TITLE
[Feature] Adding Tags to Individual Machines

### ISSUE THREAD

**Issue by SWO-andrew-shaffer** [citrix/terraform-provider-citrix#144]
**Summary:** Would like the ability to add Tag(s) to individual VDAs. Currently, the only option for tagging machines/VDAs with the Terraform provider appears to be via Machine Catalogs. Being able to individually set tags per-VDA would allow for more advanced management of things like Autoscaling, Desktop assignment within a DG, and policies.

**Is this an enhancement to an existing resource or data source, if so which one?** May be new, but could be a change to `citrix_tag`?

**If this is a new resource or data source describe what it should do.** May be enhancing `citrix_tag`, but since there isn't just a `citrix_machine` resource I'm not sure of the ideal place for this enhancement to be written.

**Link to any docs that cover this feature:**
https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/manage-deployment/tags.html

**Link to any APIs that cover this feature:**
https://developer-docs.citrix.com/en-us/citrix-daas-service-apis/citrix-daas-rest-apis/apis/#/Machines-APIs/Machines-SetMachineTags

**Comment by AlanCitrix** [comment]
Thanks for the request! The ask is clear and we will take this feature for consideration in a future release.

**Comment by AlanCitrix** [comment]
@SWO-andrew-shaffer We are trying to figure out how to best fit the machine tags into our resources. I was wondering if you would be able to share more information about your use case that requires machine tags. We support [citrix_machine_catalogs.tags](https://registry.terraform.io/providers/citrix/citrix/latest/docs/resources/machine_catalog#tags), when do specific machines need to be tagged? Also are those machines manual or MCS/PVS?

We are trying to determine the best way to fit machine tags into our resources.

**Comment by SWO-andrew-shaffer** [comment]
Hi @AlanCitrix, thanks for the question!

We're using manual machines hosted in AWS+Azure. When setting up AutoScaling where it applies to tagged machines only, just tagging a Machine Catalog isn't sufficient. Having the ability to tag individual machines will be required to take advantage of that feature of autoscaling.
