### ISSUE TITLE
[Feature] Add Enabled property for citrix_application

### ISSUE THREAD

**Issue by hewozuoai** [citrix/terraform-provider-citrix#150]
## Describe the feature request

**Summary:**
Add `Enabled` property to resource `citrix_application`

Use Case: to allow applications to be setup ready for deployment to users or removed from users without the need for removing the entire resource via terraform.

**Is this an enhancement to an existing resource or data source, if so which one?**
resource "citrix_application"
https://github.com/citrix/terraform-provider-citrix/blob/main/internal/examples/resources/citrix_application/resource.tf

**If this is a new resource or data source describe what it should do.**
N/A

**Link to any docs that cover this feature:**
N/A

**Link to any APIs that cover this feature:**
https://developer-docs.citrix.com/en-us/citrix-virtual-apps-desktops/citrix-cvad-rest-apis/apis/#/Applications-APIs/Applications-AddApplications

CitrixIssueId: 59009

**Comment by yashbhokare-citrix** [comment]
Hi @hewozuoai,

Thanks for the request! We will be adding this option in the upcoming release.

Regards,
Yash Bhokare
