### ISSUE TITLE
Option "Allow everyone with access to this delivery group to use a desktop" or "Restrict desktop use" not yet supported?

### ISSUE THREAD

**Issue by dimi4ik** [citrix/terraform-provider-citrix#19]
Hello,

I would like to set the option "Allow everyone with access to this delivery group to use a desktop" or "Restrict desktop use" via Terraform, but unfortunately, I couldn't find an option for it. Is it not supported yet, or am I doing something wrong?

Here's my Terraform code:

`resource "citrix_daas_delivery_group" "dg" {
  autoscale_enabled = false
  name              = "DG"
  associated_machine_catalogs = [
    {
      machine_catalog = citrix_daas_machine_catalog.mc.id
      machine_count   = 1
    }
  ]

  autoscale_settings = {
    disconnect_peak_idle_session_after_seconds      = 3600
    log_off_peak_disconnected_session_after_seconds = 3600
    peak_log_off_action                             = "Nothing"
    power_time_schemes = [
      {
        days_of_week = [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday"
          #"Friday"
        ]
        display_name = "weekdays schedule"
        peak_time_ranges = [
          "09:00-17:00"
        ]
        pool_size_schedules = [
          {
            "time_range" : "00:00-00:00",
            "pool_size" : 1
          }
        ],
        pool_using_percentage = false
      },
    ]
  }
}

`
If there's a way to set these options or if it's not yet supported, please let me know. 
Thank you!

**Comment by AlanCitrix** [comment]
That isn't supported yet, but we will look into adding it!

**Comment by dimi4ik** [comment]
I would like to sign up as a test/beta user. How can I do that?

**Comment by AlanCitrix** [comment]
You are already one! This provider is in preview (version is <1.0.0). You can watch this repository for new releases as we continue development.

**Comment by zhuolun-citrix** [comment]
Hi @dimi4ik ,

We have added support for desktop / application user access restriction. Please check out the latest release tagged in this issue.

Thank you!
