### ISSUE TITLE
Attribute "provisioning_scheme.machine_config.master_image" cannot be specified when "provisioning_scheme.machine_config.gallery_image" is specified

### ISSUE THREAD

**Issue by j7lloyd** [citrix/terraform-provider-citrix#21]
Of course, this is precisely what I expected; however, when I remove (or comment out) the master_image attribute, I subsequently encounter the following error:

Inappropriate value for attribute "provisioning_scheme": attribute "machine_config": attribute "master_image" is required.

**Comment by j7lloyd** [comment]
In the context of Azure Compute Gallery, Citrix recommends storing images for large non-persistent machine catalogs in Azure Compute Gallery, to facilitate quicker resets of VDA OS disks. Considering this, do you have any plans to support the placement of prepared images in Azure Compute Gallery? As per the three custom properties outlined here: https://docs.citrix.com/en-us/citrix-daas/install-configure/machine-catalogs-create/create-machine-catalog-citrix-azure.html#configure-azure-compute-gallery

**Comment by j7lloyd** [comment]
Thank you! Having just tested v0.3.5, I am pleased to confirm that it now works as expected. Please can you also log my subsequent comment (to support the placement of prepared images in Azure Compute Gallery) as a feature request?

**Comment by AlanCitrix** [comment]
Yep noted! We would love to get to that point.
