### ISSUE TITLE
FR: Support to publish/manage desktops via citrix_daas_delivery_group resource

### ISSUE THREAD

**Issue by j7lloyd** [citrix/terraform-provider-citrix#22]
Specifically, the ability to restrict launches to machines with a given tag and/or restrict desktop use to an allowed list of users. For example, I would expect the configuration block to look something like this:

resource "citrix_daas_delivery_group" "example-delivery-group" {
  name = "example-delivery-group"
  associated_machine_catalogs = [
    {
      machine_catalog = citrix_daas_machine_catalog.example-catalog.id
      machine_count = 1
    }
  ]
  **desktops = [
    {
      published_name = "_Desktop Display Name_"
      description = "_Desktop Description_"
      restrict_to_tag = "_Machine Tag Name_" 
      allowed_users = [
        "_Group/User Name_"
      ]
    }
  ]**
  ..
}

**Comment by aneeshk-citrix** [comment]
We're looking into adding this feature

**Comment by zhuolun-citrix** [comment]
Hi @j7lloyd ,

We have just added support for managing desktops via user access restriction. Please check out the latest release tagged in the issue. 

Thank you.
