### ISSUE TITLE
Future Implementation of Microsoft Hyper-V (VMM) as Power Managed Hypervisor

### ISSUE THREAD

**Issue by dimi4ik** [citrix/terraform-provider-citrix#37]
Hello everyone,

According to the latest release notes, the manual Power Managed Machine Catalog now supports the hypervisors Vsphere, XenServer, and Nutanix.

We would like to discuss the possibility of integrating Microsoft Hyper-V (VMM) as a Power Managed Hypervisor as well.

Could we please initiate a discussion to explore if this implementation is planned for the future?
Thank you in advance for your assistance.

Best regards,
Dim

**Comment by zhuolun-citrix** [comment]
Hi @dimi4ik ,

Thank you for your request. We will take this as a feature request for supporting SCVMM as a Power Managed Hypervisor. We don't have an ETA for this yet but will keep it in our bucket.

Thank you!

**Comment by matthias-schlimm** [comment]
@zhuolun-citrix  I'm looking for SCVMM Provider too. It would be good to have this too. 

I know, with Azure Stack HCI and Azure Arc it's more pressure on this. 

One of my big customer has running the whole Citrix Environment Running on MS S2D, and for the deployment of on-demand persistent VDI's with Citrix Cloud it's easy to use with terraform if wqe have the right provider.
