### ISSUE TITLE
citrix_machine_catalog - Cannot set functional level

### ISSUE THREAD

**Issue by kgilbertwams** [citrix/terraform-provider-citrix#41]
I'm not seeing a way to set the functional level of the catalog (2108, 2203, etc) from the documentation. Can you confirm if this is possible now, and if not if it will be in a future release?

**Comment by zhuolun-citrix** [comment]
Hi @kgilbertwams ,

Thank you for raising this issue. Currently the functional level is not configurable via terraform and is hard coded to be `L7_20`. We will take this as a feature request. Support for setting functional level will be added in a future release.

Thank you!
