### ISSUE TITLE
Citrix Daas Machine Catalog Allocation type "Static" is not working with MultiSession VMs.

### ISSUE THREAD

**Issue by venugopal-chinnasamy** [citrix/terraform-provider-citrix#44]
Hello,

I got an error below when i created MC with allocation type "Static" with MultiSession VMs.

"provider[\"registry.terraform.io/citrix/citrix\"]" produced an unexpected new value: .allocation_type: was
│ cty.StringVal("Static"), but now cty.StringVal("Random").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by zhuolun-citrix** [comment]
Hi @venugopal-chinnasamy ,

Thank you for raising this issue. `Static` allocation type is not supported when using `MultiSession` session support. We will take this as a bug and enforce validation on the schema.

Thank you.
