### ISSUE TITLE
citrix_policy_set - Error message: 501 Not Implemented

### ISSUE THREAD

**Issue by kgilbertwams** [citrix/terraform-provider-citrix#46]
I'm trying to deploy a basic policy set with the bare minimum settings to just to get it to deploy, and then plan on evolving it from there to match our desired policy settings. However, when I try to deploy I receive the below error message. Can you provide a bare minimum configuration to get the policy set to deploy? Here is what I'm trying now:

```
resource "citrix_policy_set" "default_policy" {
    name = "example-policy-set"
    description = "This is an example policy set description"
    type = "DeliveryGroupPolicies"
    scopes = [ "All" ]
    policies = [
        {
            name = "test-policy-with-priority-1"
            description = "Test policy in the example policy set with priority 1"
            is_enabled = false
            policy_settings = []
            policy_filters = []
        }
    ]
}
```
The plan works successfully, but when I try to deploy I get this error about about 1m 40s:

```
citrix_policy_set.default_policy: Still creating... [1m40s elapsed]
╷
│ Error: Error Reading Policy Sets
│
│   with citrix_policy_set.default_policy,
│   on policy_sets.tf line 3, in resource "citrix_policy_set" "default_policy":
│    3: resource "citrix_policy_set" "default_policy" {
│
│ TransactionId: f459e33a-a25e-40fe-9b4f-064161a024d1
│ Error message: 501 Not Implemented
╵
╷
│ Error: Unexpected error in the Citrix provider
│
│   with citrix_policy_set.default_policy,
│   on policy_sets.tf line 3, in resource "citrix_policy_set" "default_policy":
│    3: resource "citrix_policy_set" "default_policy" {
│
│ An unexpected error occurred in runtime.panicmem.
│
│ runtime error: invalid memory address or nil pointer dereference
│
│ Please report this issue to the project maintainers and include this file if present: C:\Users\kevin\AppData\Local\Temp\citrix_provider_crash_stack.1696142859.txt
╵
```

I've uploaded the crash text file below:

[citrix_provider_crash_stack.1696142859.txt](https://github.com/citrix/terraform-provider-citrix/files/14566740/citrix_provider_crash_stack.1696142859.txt)

**Comment by zhuolun-citrix** [comment]
Hi @kgilbertwams ,

Currently, GPO feature is available to Citrix on-premises customers who is on DDC version 2402 or higher. For Citrix Cloud customers, this feature is currently unavailable. But it will be coming to Citrix Cloud customers soon. Please stay tuned!

We will update the terraform documentation on registry to reflect the availability of this feature. Marking this as a bug in documentation and will fix it in next release.

Thank you for reporting this issue!

**Comment by kgilbertwams** [comment]
I just tried again and got the 501 error again on 0.5.3. I checked the other issues I reported and they were all resolved, but this issue is persisting. Error output below:

```
╷
│ Error: Error Reading Policy Sets
│
│   with module.citrix_cloud_daas[0].citrix_policy_set.default_policy,
│   on .terraform\modules\citrix_cloud_daas\policy_sets.tf line 3, in resource "citrix_policy_set" "default_policy":
│    3: resource "citrix_policy_set" "default_policy" {
│
│ TransactionId: 56999022-507d-4328-aa65-c1d5bab5c8b8
│ Error message: 501 Not Implemented
╵
╷
│ Error: Unexpected error in the Citrix provider
│
│   with module.citrix_cloud_daas[0].citrix_policy_set.default_policy,
│   on .terraform\modules\citrix_cloud_daas\policy_sets.tf line 3, in resource "citrix_policy_set" "default_policy":
│    3: resource "citrix_policy_set" "default_policy" {
│
│ An unexpected error occurred in runtime.panicmem.
│
│ runtime error: invalid memory address or nil pointer dereference
│
│ Please report this issue to the project maintainers and include this file if present: C:\Users\<username>\AppData\Local\Temp\citrix_provider_crash_stack.2714440954.txt
```

**Comment by aneeshk-citrix** [comment]
Hi @kgilbertwams,

Are you using a cloud customer or an On-Premises customer? And if using an On-Premises, what is your DDC version?

Aneesh
