### ISSUE TITLE
Deploying full Entra ID (AAD) catalog in DAAS

### ISSUE THREAD

**Issue by lordavid86** [citrix/terraform-provider-citrix#47]
Hi
We are trying to deploy a machine catalog on Azure, using native Azure AD. 
The code seems to work, the machines are created and register, but we have an error message and it seems terraform stops the deployment, therefore skipping the next items (DVG, apps, policies, …)

_**When applying changes to citrix_machine_catalog.AZ-ITOR-POOL, provider "provider(\"registry.terraform.io/citrix/citrix\"]" produced an unexpected new
value: •provisioning_scheme.machine_domain_identity: was null, but now cty.ObjectVal(map[string)cty.Value{"domain":cty.NullVal(cty. strinmin_ou":cty.MullVal (cty.String), "service_account" cty. NulVal (cty.String), "service account_password":cty.ulVel (cy.String))

This is a bug in the provider, which should be reported in the provider’s own issue tracker**_. 

As we use AAD, the machine_domain_identity schema is not appropriate and seems to cause this error, but we couldn’t find the correct parameters for our use case 

thanks for your help 
Best regards

**Comment by aneeshk-citrix** [comment]
Hi @lordavid86,

Thank you for bringing this issue to our attention. We are looking into fixing this issue and it should be available in the next release.

Aneesh

**Comment by lordavid86** [comment]
Thank you !
I have another question related to this scenario we are trying to achieve. When restricting access to apps or desktops, what is the correct format for username ? We tried user@domain.com and AzureAD\user@domain.com as doc specify to use domain\user but it returns an error 
Thanks 
Regards

**Comment by aneeshk-citrix** [comment]
Hi @lordavid86,

For now, we only support restricting users from Active Directory. We are working on supporting users from Azure AD and also add the missing parameters that you mentioned. These will be available in a future release. 

We will tag this as a bug to fix the original issue first. Once we have the bug fix, we will change it to enhancement.

Thanks,
Aneesh
