### ISSUE TITLE
Importing Resource Location or Zone - Requires Uid instead of ExternalUid

### ISSUE THREAD

**Issue by amshaffer** [citrix/terraform-provider-citrix#50]
Running `terraform import citrix_zone.zone EXTERNAL-UID-HERE` returns "Cannot import non-existent remote object" when specifying the ExternalUid of a resource location. It works fine if the Uid is used instead.

When manually creating a resource location in the Citrix Cloud web console, the ID listed there is the ExternalUid. The only way I've been able to find the Uid is via PowerShell with Get-ConfigZone. Is it possible to use the ExternalUid with this zone import instead of having to first retrieve the Uid via powershell?

**Comment by aneeshk-citrix** [comment]
Hi @amshaffer,

We are expecting a Zone ID here and not a Resource Location ID that is exposed in the Citrix Cloud UI. We have plans to expose the resource ID in the webstudio UI so it is easily available for use in terraform.
For now, another way to get the zone ID is through inspecting the network calls in the browser dev tools when loading Zones in the webstudio UI.

Also as an alternative to importing zone, you can have a matching terraform config for your existing zone resource and run apply which will adopt your existing zone resource into terraform state.

Aneesh

**Comment by amshaffer** [comment]
Makes sense, thanks very much! This will be easy enough to work through with your recommendations.
