### ISSUE TITLE
Building Machine Catalog from Variables

### ISSUE THREAD

**Issue by amshaffer** [citrix/terraform-provider-citrix#55]
I'm trying to use variables for deploying an AWS-hosted manual machine catalog with multiple VDAs, and I'm getting the following error when running `terraform plan`. I'm sure I've just done something wrong or not expected, but would appreciate a bit of help to see if this is something in the provider.

```
> terraform plan
╷
│ Error: Value Conversion Error
│
│   with citrix_machine_catalog.aws-catalog,
│   on machine_catalogs.tf line 1, in resource "citrix_machine_catalog" "aws-catalog":
│    1: resource "citrix_machine_catalog" "aws-catalog" {
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the
│ following to the provider developer:
│
│ Received unknown value, however the target type cannot handle unknown values. Use the corresponding `types` package type or a
│ custom type that handles unknown values.
│
│ Path: machine_accounts[0].machines
│ Target Type: []machine_catalog.MachineCatalogMachineModel
│ Suggested Type: basetypes.ListValue
```

The output that this is an error in the provider made me decide to open this bug, despite thinking I've probably built the variables incorrectly. Is there a straightforward way to use the MachineCatalogMachineModel type in this fashion with variables, or some other method to achieve this goal?

variables.tf:
```
variable "machines" {
  type = list(object({
    machine_account   = string
    machine_name      = string
    availability_zone = string
  }))
  description = "VDA details"
}
```

terraform.tfvars:
```
machines = [
  {
    machine_account   = "DOMAIN\\VDA1"
    machine_name      = "i-12345678"
    availability_zone = "us-east-1"
  },
  {
    machine_account   = "DOMAIN\\VDA2"
    machine_name      = "i-87654321"
    availability_zone = "us-east-1"
  }
]
```

And the relevant code in the machine catalog resource:
```
  machine_accounts = [
    {
      hypervisor = citrix_aws_hypervisor.aws-hypervisor.id
      machines   = var.machines
    }
  ]
```

Thank you!

**Comment by xushengl** [comment]
Hi @amshaffer 

Thanks for reporting this issue, we will investigate it and keep you posted.

Xusheng "Fred" Liu

**Comment by xushengl** [comment]
Hi @amshaffer

At the current point, we cannot use variables for `machine_accounts.machines`. Please input the list directly for now. We will let you know when we add support to use the list variable.

Xusheng "Fred" Liu

**Comment by amshaffer** [comment]
@xushengl Got it, thanks!
