### ISSUE TITLE
Terraform plan/apply with AWS shows error

### ISSUE THREAD

**Issue by SLemonier** [citrix/terraform-provider-citrix#59]
Hello guys,

Not sure if it's a terraform bug or if it's related to the provider but when I do a terraform plan, I get this:
![CleanShot 2024-04-11 at 17 08 14](https://github.com/citrix/terraform-provider-citrix/assets/20860016/564278ee-e7bc-44c1-9f50-bbbdaa7b9a1c)

Same behaviour when I run terraform apply and nothing is created.

Thanks,
Steven

**Comment by SLemonier** [comment]
Same behaviour when I run terraform apply

**Comment by aneeshk-citrix** [comment]
Hi @SLemonier,

With release v0.3.6, we have per connection type hypervisor and per connection type hypervisor resource pool. And with release v0.5.0, we removed `daas` from resource names.

If you have resources created from before these releases, you can either update the state file to reflect the correct resource names or clean the state file and import these resources and run apply again. Please ensure all resource names in the tf files are also updated.

Thanks,
Aneesh

**Comment by SLemonier** [comment]
Hello @aneeshk-citrix 

I deleted the resources, state files and so on, now I don't see the error anymore.

Thanks,
Steven
