### ISSUE TITLE
Creating a computer account fails

### ISSUE THREAD

**Issue by SLemonier** [citrix/terraform-provider-citrix#60]
Dear all,

I tried to create a machine catalog using the provider and I face the following error:
│   with citrix_machine_catalog.AAA-TF,
│   on machine_catalog.tf line 1, in resource "citrix_machine_catalog" "AAA-TF":
│    1: resource "citrix_machine_catalog" "AAA-TF" {
│ 
│ TransactionId: 4e2e6eab-a195-4091-9998-64a4447217f9
│ JobId: f5f8b338-9e11-4901-a351-a82ddb70ad7a
│ Error message: Failed to create a computer account SDNE20001, due to an unknown error.

I successfully created a machine catalog manually with the same parameters.

May I ask you to check please?

Thanks,
Steven

**Comment by aneeshk-citrix** [comment]
Hi @SLemonier,

From the logs, there seems be a problem authenticating to the domain. Can you make sure you are using the correct username and password and that the password hasn't expired.

Thanks,
Aneesh

**Comment by SLemonier** [comment]
I am 100% sure, I used the same account to manually create the machine catalog.

**Comment by aneeshk-citrix** [comment]
@SLemonier What is the format of the input that you are passing in for the service_account? Please note that we only expect the username and not domain\username.

Thanks,
Anessh

**Comment by SLemonier** [comment]
Ah correct, I removed domain\ but now it failed with:

│ TransactionId: ce0ee8ba-9869-4122-9c41-4e63cce7e86b
│ JobId: a0bd4666-a98c-4ad9-95f9-8501a17dc796
│ Error message: Failed to create the virtual machine; RCCAD\SDNE20002$.

**Comment by aneeshk-citrix** [comment]
@SLemonier,

The error I see is - You do not have access to a default security group in VPC vpc-05d0f96b3f84d67ee. Specify a security group, and try again.

Can you share your tf config for machine catalog? Specifically, we are looking for `network_mapping`.

**Comment by SLemonier** [comment]
I used this code for the network_mapping:

network_mapping = {
            network_device = "0"
            network = citrix_aws_hypervisor_resource_pool.NPRD-RIC-EUC-1A-TF.subnets[0]
        }

**Comment by aneeshk-citrix** [comment]
What is the value for network?

**Comment by aneeshk-citrix** [comment]
@SLemonier Can you also make sure the service account you provided to create the hypervisor has enough permissions to perform write operation on the security group for the VPC and VPC subnet you are using.

**Comment by aneeshk-citrix** [comment]
@SLemonier When you use Studio UI to create machine catalog, what do you choose in the `Security` section. Is it default or something else?

**Comment by SLemonier** [comment]
I use default choice:
![CleanShot 2024-04-16 at 14 05 21](https://github.com/citrix/terraform-provider-citrix/assets/20860016/fc90ab1a-5329-42f3-aaba-90a5b2b024a2)
