### ISSUE TITLE
Terraform Onboarding script - Hypervisor - unreadable characters

### ISSUE THREAD

**Issue by ladanovy** [citrix/terraform-provider-citrix#63]
Hello,

Due processing of the onboard script getting an error : 
terraform : [31m[31mâ•·[0m[0m
At C:\test\Terraform\Project2_Test\terraform-onboarding.ps1:599 char:1
+ terraform fmt
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([31m[31mâ•·[0m[0m:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mInvalid character[0m
[31mâ”‚[0m [0m
[31mâ”‚[0m [0m[0m  on resource.tf line 46, in resource "citrix_machine_catalog" "machine_catalog_0":
[31mâ”‚[0m [0m  46:             hypervisor = [4m[0m[90mnull[0m[0m[0m
[31mâ”‚[0m [0m
[31mâ”‚[0m [0mThis character is not used within the language.

When I check the resource.tf file - on suggested line I can see **hypervisor = [90mnull[0m[0m**
In WebStudio is only one MC with name PROD - Windows Server 2022 set with Provisioning method manual. Machines there are provisioned by PVS.
There is no hosting connection set.

# citrix_machine_catalog.machine_catalog_0:
resource "citrix_machine_catalog" "machine_catalog_0" {
    allocation_type          = "Random"
    description              = "PROD - Windows Server 2022"
    is_power_managed         = false
    is_remote_pc             = false
    machine_accounts         = [
        {
            **hypervisor = [90mnull[0m[0m**
            machines   = [
                {
                    machine_account = "wp\\wp-xd01"
                },
            ]
        },
    ]
    
   Have I done anything wrong ?

**Comment by zhuolun-citrix** [comment]
Hi @ladanovy ,

Unfortunately, PVS is not yet supported by our hypervisor. The only supported provisioning type is `Manual` or `MCS`.

**Comment by ladanovy** [comment]
Hello,
Thanks and understand.  But still the method there is manual - would be possible to just make sure that the hypervisor would be "nothing" instead of those characters ? It would be really helpfull during onboarding.

**Comment by zhuolun-citrix** [comment]
@ladanovy ,

May I ask if you are running terraform on Jenkins? Looks like the cmd tool you are running terraform with does not have the AnsiColor color plugin to render the logs with proper font colors.

Without the ability to render the font colors in your cmd environment, the color code becomes part of the value which violates the validator. As you can see in the error message 
```�[31mâ”‚�[0m �[0m�[0m on resource.tf line 46, in resource "citrix_machine_catalog" "machine_catalog_0":
�[31mâ”‚�[0m �[0m 46: hypervisor = �[4m��[0m[90mnull�[0m�[0m�[0m
�[31mâ”‚�[0m �[0m
�[31mâ”‚�[0m �[0mThis character is not used within the language.```

The error is complaining about invalid characters. That could be the reason why it's failing for you.

**Comment by ladanovy** [comment]
Hi,
It was run via Powershell ISE. I just did a test with powershelf itself and it also fails with expresion: 
 hypervisor = [90mnull

![image](https://github.com/citrix/terraform-provider-citrix/assets/12028172/6c40cfc9-6cb0-451b-b2fb-6fe5b5f0b121)

**Comment by zhuolun-citrix** [comment]
Hi @ladanovy ,

Could you please try cleaning up all the generated files including `citrix.tf` and rerun the script in powershell with only `terraform-onboarding.ps1` and `terraform.tf`?

If you look into the screenshot, `[90m` color code was properly rendered in the last line where `null` was shown in grey fonts. Looks like it's running on some previously generated terraform code that still has the uninterpreted color code, which messed up the terraform TF syntax.

Please rerun the script in a new folder or after cleaning up all the generated files apart from the script itself and `terraform.tf`. Hopefully that could solve the issue.

**Comment by zhuolun-citrix** [comment]
Hi @ladanovy ,

Any luck with rerunning from fresh in actual PowerShell?

**Comment by ladanovy** [comment]
Hello @zhuolun-citrix 
When I did my testing I always used new folder, made a copy of ps1 script together with terraform.tf as it is described in howto document.
I did that once more again now.
New folder,copy of terraform.tf and ps1 script, terraform init as you can see on the picture
![image](https://github.com/citrix/terraform-provider-citrix/assets/12028172/d9ffe7fd-0149-443c-9df3-d6841c12cb28)
And finally run of the onboarding.ps1
![image](https://github.com/citrix/terraform-provider-citrix/assets/12028172/22f34468-c901-43b8-aa97-532af3f4fc39)

:) no luck unfortunately.

**Comment by zhuolun-citrix** [comment]
Hi @ladanovy ,

We have been working on identifying the issue. We will have a fix for skipping PVS catalog imports in the onboarding script so that this issue doesn't block supported resource types from being imported. 

Please expect a fix for the issue in the next release.

Thank you.
