### ISSUE TITLE
Building a Machine Catalog in Azure - Image must be in the same subscription.

### ISSUE THREAD

**Issue by TimBennett13** [citrix/terraform-provider-citrix#71]
Hello,
I am building a machine catalog in an Azure subscription where the image vhd is in our "core" infrastructure subscription and we want to create Machine Catalogs in other subscriptions. I verified this by having a storage account and vhd on blob storage then setting the _resource_group_ value to the Azure resource group where the storage account is. This resource group is in a different subscription than _vda_resource_group_. I get an error on _terraform apply_ saying the image is not found. If I move the storage account to the same resource group as the _vda_resource_group_ and change the image _resource_group_ value to the same it works as expected. I upgraded the provider to 0.6.0.
I'm troubleshooting the functionality with a vhd and storage account but the preferred method is a compute gallery image.

Thanks,
Tim

**Comment by aneeshk-citrix** [comment]
Hi @TimBennett13,

We added a new property called `shared_subscription` as a part of `azure_master_image`. If the vhd is in a subscription different from what was used to create the hypervisor connection, you need to use this property. Are you already using this?

Here's a link  to the documentation for `shared_subscription` - 
https://registry.terraform.io/providers/citrix/citrix/latest/docs/resources/machine_catalog#nested-schema-for-provisioning_schemeazure_machine_configazure_master_image

Thanks,
Aneesh

**Comment by TimBennett13** [comment]
Hello Aneesh,
Thank you for your rapid response. I am not using the shared_subscription property. Thank you so much for pointing it out I'm adding it now.

Thanks,
Tim

**Comment by TimBennett13** [comment]
The issue was that I didn't review the documentation after the last update.
