### ISSUE TITLE
[Feature Request] - Application user group and icons

### ISSUE THREAD

**Issue by jdestombes** [citrix/terraform-provider-citrix#73]
Hello,

Is it possible to add properties for user group and icons in citrix_application ressource ?

We can create appication but only with default icon and visibility for all delivery group users.

Thanks !

**Comment by aneeshk-citrix** [comment]
Hi @jdestombes,

Just to clarify, what do you mean by user groups? Do you mean restricting access to the application?

Thanks,
Aneesh

**Comment by jdestombes** [comment]
Ji,

Yes. I want to be able to specify user groups to restrict access.



Regards,




Julien DESTOMBES
Practice Leader - Workspace et Platform
+33 6 64 67 68 55
<http://constellaction.com/content/formulaire/index.php>[cid:anetys_2-2021vect-quadri_386d58bf-9d2d-485e-bc1a-1189ba9bfe59.png]
Lille - Paris - Strasbourg - Nantes - Lyon - Toulouse

Standard : +33 1 88 89 08 70 / Support technique : +33 1 88 88 34 14
62 avenue Jean-Baptiste Lebas - 59100 Roubaix
www.anetys.com<http://www.anetys.com/>

[cid:linkedIn_small_df52b9d8-c22f-4384-94c5-3ed162ea05dd.png]<https://fr.linkedin.com/company/anetys>  [cid:twitter_small_40357e7d-f3a9-47eb-b314-1889db0f9dc0.png] <https://twitter.com/anetys_fr>

________________________________
De : aneeshk-citrix ***@***.***>
Envoyé : vendredi 31 mai 2024 17:02
À : citrix/terraform-provider-citrix ***@***.***>
Cc : Julien DESTOMBES ***@***.***>; Mention ***@***.***>
Objet : Re: [citrix/terraform-provider-citrix] [Feature Request] - Application user group and icons (Issue #73)


Hi @jdestombes<https://github.com/jdestombes>,

Just to clarify, what do you mean by user groups? Do you mean restricting access to the application?

Thanks,
Aneesh

**Comment by aneeshk-citrix** [comment]
Out of curiosity, are you able to do this using the WebStudio UI or are you using something else to achieve this?

**Comment by amshaffer** [comment]
+1 on this. This is something you can do in Studio/Web Studio via the "Limit Visibility" option of an application and would be very helpful.

**Comment by aneeshk-citrix** [comment]
Understood. Thanks @amshaffer 

Marking this as a feature request. We'll prioritize on the ability to restrict users. 

For icons, how would you like to specify them?

-Aneesh

**Comment by jdestombes** [comment]
Perhaps base64 icon code could be a solution.

Don't know if other solution is possible.

Cordialement.



Julien DESTOMBES
Practice Leader - Workspace et Platform
+33 6 64 67 68 55
<http://constellaction.com/content/formulaire/index.php>[cid:anetys_2-2021vect-quadri_386d58bf-9d2d-485e-bc1a-1189ba9bfe59.png]
Lille - Paris - Strasbourg - Nantes - Lyon - Toulouse

Standard : +33 1 88 89 08 70 / Support technique : +33 1 88 88 34 14
62 avenue Jean-Baptiste Lebas - 59100 Roubaix
www.anetys.com<http://www.anetys.com/>

[cid:linkedIn_small_df52b9d8-c22f-4384-94c5-3ed162ea05dd.png]<https://fr.linkedin.com/company/anetys>  [cid:twitter_small_40357e7d-f3a9-47eb-b314-1889db0f9dc0.png] <https://twitter.com/anetys_fr>

________________________________
