### ISSUE TITLE
[Feature Request] Create Delivery Group - Add Local Host Cache support

### ISSUE THREAD

**Issue by TimBennett13** [citrix/terraform-provider-citrix#76]
When I create a delivery group it is created with out Local Host Cache support. I failed to see any options for LHC in the Delivery Group doc.

Thanks,
Tim

**Comment by aneeshk-citrix** [comment]
Hi @TimBennett13,

Thanks for bringing this up. We will work on making the LHC support available in Delivery Group.

Aneesh
