### ISSUE TITLE
Create Delivery Group - Allow List AD Group Error in output

### ISSUE THREAD

**Issue by TimBennett13** [citrix/terraform-provider-citrix#77]
I created a Delivery Group and an error was thrown that it couldn't find the AD group in the allow list yet the DG is created and the group is assigned to desktops.

`citrix_delivery_group.dev-MyTerraform-DG: Creating...
╷
│ Error: Error fetching delivery group user details
│
│   with citrix_delivery_group.dev-MyTerraform-DG,
│   on main.tf line 11, in resource "citrix_delivery_group" "dev-MyTerraform-DG":
│   11: resource "citrix_delivery_group" "dev-MyTerraform-DG" {
│
│ TransactionId: 0bc2a2de-a0a4-401b-96aa-399c544ca251
│ Error message: The following users could not be found: {domain}\dev-MyTerraform`

**Comment by j7lloyd** [comment]
@TimBennett13, I've observed this issue as well, both directly under the DG block and in the context of the nested `desktops` argument. It used to work as expected in release 0.5.8, so I'm confident this issue is specific to the new 0.6.0 release.

**Comment by aneeshk-citrix** [comment]
Hi @TimBennett13, @j7lloyd,

We are aware of this issue and actively working on fixing it.

Thanks,
Aneesh
