### ISSUE TITLE
Terraform - Storefront

### ISSUE THREAD

**Issue by mashab28** [citrix/terraform-provider-citrix#84]
provider "citrix" {
  hostname      = 
  customer_id   = 
  environment   = 
  client_id     = 
  client_secret = 
  disable_ssl_verification =
    storefront_remote_host = {
    computer_name = "{Name of the remote computer where the StoreFront located}"
    ad_admin_username ="{Active Directory Admin Username}"
    ad_admin_password ="{Active Directory Admin Password}"
  }
}

Do we need to use hostname field for deploying storefront via terraform ? if Yes, any version requirement for DDC and do we need Webstudio ?

Thanks

**Comment by xushengl** [comment]
Hello @mashab28 

As of the latest released version (`v0.6.1`) In the OnPrem environment, we do need to specify the following parameters aside from the `storefront_remote_host` block. Theses parameters will help in establishing connection to the DDC.
```
hostname
client_id
client_secret
disable_ssl_verification
```

We will work on an enhancement to remove the dependency on DDC connection parameters when only StoreFront parameters are needed.

For managing StoreFront only, we don't have specific requirement on DDC version as long as WebStudio is available. However, we would recommend using DDC version 2402 LTSR.

Best Regards,
Xusheng "Fred" Liu
