### ISSUE TITLE
Citrix Storefront Terraform

### ISSUE THREAD

**Issue by mashab28** [citrix/terraform-provider-citrix#85]
Hi,

Is it possible to add multiple farms under farm_config and detailed configurations while creating Storefront store via terraform ?

**Comment by xinghengl-citrix** [comment]
Hello @mashab28 

We are aware of the need to support multiple farms. Currently, we are working on enhancing farm_config to be an independent resource. This enhancement will enable support for multiple farms with detailed configurations

Best Regards,
Xingheng Lin
