### ISSUE TITLE
Cannot make any change post creating an icon resource.

### ISSUE THREAD

**Issue by prasanthrs6** [citrix/terraform-provider-citrix#95]
## Describe the bug

Once I finish creating an icon via terraform any consecutive actions including terraform plan are erroring out.

## Versions
0.6.3

## Terraform configuration files
resource "citrix_application_icon" "bank-icon" {
  raw_data = filebase64("/icons/bank.ico")
}

## Terraform console output
│ Error: Error Reading Application Icon 221
│
│   with citrix_application_icon.bank-icon,
│   on icons.tf line 2, in resource "citrix_application_icon" "bank-icon":
│    2: resource "citrix_application_icon" "bank-icon" {
│
│ TransactionId: 539c074e-40e4-4f09-bf01-84893133074e
│ Error message:

*If the output references a file in the temp directory include it as well.*

**Comment by aneeshk-citrix** [comment]
Hi @prasanthrs6,

Would it be possible to create another icon? You can have the same raw data but provide a different resource name.
To move past the error, you might have to remove the resource you created manually from the state file.

We had a look at the raw data and it seems large. Do you think you can also try with an icon with a smaller size?

Let us know how it goes.

Thanks,
Aneesh

**Comment by prasanthrs6** [comment]
@aneeshk-citrix I removed the reference from state file and tried creating new icon resources via terraform using different files and also tried with different sizes (1kb to 67kb) still seeing the same issue.

**Comment by prasanthrs6** [comment]
@aneeshk-citrix  yes, I am able to get past the error after removing the icon resources from the state file. As long as I am not creating icon resources via terraform I am not having any issues.

**Comment by aneeshk-citrix** [comment]
Ok we're continue to look into this issue. Will keep you posted.
Can you set the log to debug, reproduce the issue and post the logs?

set TF_LOG="DEBUG"
set TF_LOG_PATH="./citrix-provider-issue.txt"

and then run terraform

**Comment by aneeshk-citrix** [comment]
Hi @prasanthrs6,

We have found the issue and working on a fix.

Thanks again for reporting, we'll have a fix out soon.

Aneesh
